"""Adding tags and link table

Revision ID: 106bfde224ec
Revises: ab3e47fb856c
Create Date: 2021-09-21 14:51:45.361990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106bfde224ec'
down_revision = 'ab3e47fb856c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('response_tag',
    sa.Column('response_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
