"""test

Revision ID: 2a1b1ddb98f3
Revises: d49d1b115d31
Create Date: 2021-09-20 14:40:38.560187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a1b1ddb98f3"
down_revision = "d49d1b115d31"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("response", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response", "is_active")
    # ### end Alembic commands ###
