"""Add is_active column

Revision ID: 836e9fb3e939
Revises: ab3e47fb856c
Create Date: 2021-09-21 14:52:00.541489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "836e9fb3e939"
down_revision = "ab3e47fb856c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("response", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("response", "is_active")
    # ### end Alembic commands ###
