name: CI

on:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: |
          pip install poetry
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry config pypi-token.pypi ${{ secrets.POETRY_PYPI_TOKEN }}
      - run: poetry build
      - run: poetry publish
  build:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            APP_VERSION=${{ github.ref_name }}
          tags: |
            ghcr.io/${{github.repository}}:${{ github.ref_name }}
            ghcr.io/${{github.repository}}:latest
