"""callback action

Revision ID: 76feeb81949a
Revises: 7b4efa0dd5ea
Create Date: 2021-10-19 10:05:49.346229

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "76feeb81949a"
down_revision = "7b4efa0dd5ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE action ADD VALUE 'CALLBACK'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
