"""storage

Revision ID: f0be9a5e8cec
Revises: d42bddfac4f1
Create Date: 2022-11-04 20:22:43.252600

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f0be9a5e8cec"
down_revision = "d42bddfac4f1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE action ADD VALUE 'STORE'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
